osx_image: xcode7.2
language: objective-c
cache: cocoapods
before_install:
- export LANG=en_US.UTF-8
- env
- locale
- gem install cocoapods xcpretty # Since Travis is not always on latest version
- pod --version
- curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.11/Carthage.pkg"
- sudo installer -pkg "Carthage.pkg" -target /
- rm "Carthage.pkg"
script:
- open -b com.apple.iphonesimulator # Travis CI workaround
- set -o pipefail && xcodebuild test -workspace Bitter.xcworkspace -scheme "Bitter" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- carthage build --no-skip-current
- pod lib lint --quick
