osx_image: xcode7.2
language: objective-c
cache: cocoapods
before_install:
- export LANG=en_US.UTF-8
- env
- locale
- gem install cocoapods xcpretty # Since Travis is not always on latest version
- pod --version
script:
- set -o pipefail && xcodebuild -workspace Bitter.xcworkspace -scheme "BitterSwift" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 5s,OS=8.0" ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint
